### ISSUE TITLE
add support for the automatic answering the questions in qgraph. [detector]

### ISSUE THREAD

**Issue by andyliuliming** [Microsoft/kunlun#8]
say, the "detector: github.com/Microsoft/kunlun/language_detector" element in 

```
- name: language
  questions:
    - var_name: "language_kind"
      description: "Which kind of language are you using?"
      detector: github.com/Microsoft/kunlun/language_detector
      candidates:
        - value: php
          description: "Your project are using php language."
```
